glue.c: update to new uk_alloc_init_malloc interface
unikraft/lib-tlsf pull request #2
Opened 2021-06-25 10:49 UTC by hlef

The uk_alloc_init_malloc interface has been updated with maxalloc and
availmem. We must update calls accordingly.

Signed-off-by: Hugo Lefeuvre <hugo.lefeuvre@manchester.ac.uk>

2021-08-02 10:11 UTC, skuenzer requested changes
Hi Hugo,

thanks a lot for this work. Can you also add the following changes? It is because commit unikraft/unikraft@ed1ef9aef 
removed the usage of libc type definitions within `uk/alloc.h` in order to avoid include conflicts with libc's.

`include/uk/tlsf.h`:
```diff
+#include <stddef.h> /* `NULL` and `size_t` */
```

`glue.c`:
```diff
+#include <stdint.h> /* uintptr_t */
```

As alternative, you can also change the used types in the header and the glue code to match Unikraft internal ones (e.g., `__NULL`, `__sz`, `__uptr`).

Thanks,

Simon

2021-08-09 15:47 UTC, razvand reviewed
Hi, @hlef . I second the comments from @skuenzer on including header files to make TLSF work with `nolibc`. With those in place, all is well.

2021-08-09 18:31 UTC, hlef commented
Hi @razvand and @skuenzer, thanks for the review. I have updated the patch.

2021-08-10 16:38 UTC, skuenzer approved these changes
Looks good to me, thanks!

Reviewed-by: Simon Kuenzer <simon.kuenzer@neclab.eu>

2021-08-11 07:45 UTC, razvand approved these changes
All good.

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

2021-11-27 14:16 UTC, razvand commented
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

2021-11-27 18:32 UTC, closed without merging